<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
         $products = [
            // ADMIN PRODUCTS (1-10) - vendor_id = 0
            [
                'name' => 'iPhone 15 Pro',
                'slug' => 'iphone-15-pro',
                'thumb_image' => 'uploads/products/iphone15pro.jpg',
                'admin_id' => 1,
                'vendor_id' => 0,
                'category_id' => 1,
                'sub_category_id' => 1,
                'child_category_id' => 2,
                'brand_id' => 1,
                'qty' => 100,
                'short_description' => 'A17 Pro chip, Titanium design',
                'long_description' => '6.1" Super Retina XDR, 48MP camera, Dynamic Island',
                'video_link' => 'https://youtu.be/iphone15',
                'sku' => 'APPIP15P128',
                'price' => 999.00,
                'offer_price' => 949.00,
                'offer_start_date' => '2023-10-01',
                'offer_end_date' => '2023-12-31',
                'product_type' => 'new_arrival',
                'status' => true,
                'is_approved' => 1,
                'seo_title' => 'iPhone 15 Pro - Apple',
                'seo_description' => 'Latest iPhone with titanium body',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'MacBook Pro 14" M2',
                'slug' => 'macbook-pro-14-m2',
                'thumb_image' => 'uploads/products/macbookpro14.jpg',
                'admin_id' => 1,
                'vendor_id' => 0,
                'category_id' => 1,
                'sub_category_id' => 2,
                'child_category_id' => 4,
                'brand_id' => 1,
                'qty' => 50,
                'short_description' => 'M2 Pro/Max chip, XDR display',
                'long_description' => '14.2" Liquid Retina XDR, up to 96GB RAM, 8TB SSD',
                'video_link' => null,
                'sku' => 'APPMBP14M2',
                'price' => 1999.00,
                'offer_price' => null,
                'offer_start_date' => null,
                'offer_end_date' => null,
                'product_type' => 'featured_product',
                'status' => true,
                'is_approved' => 1,
                'seo_title' => 'MacBook Pro 14" M2',
                'seo_description' => 'Professional laptop for creatives',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Sony WH-1000XM5',
                'slug' => 'sony-wh-1000xm5',
                'thumb_image' => 'uploads/products/sony-headphones.jpg',
                'admin_id' => 1,
                'vendor_id' => 0,
                'category_id' => 1,
                'sub_category_id' => null,
                'child_category_id' => null,
                'brand_id' => 3,
                'qty' => 75,
                'short_description' => 'Noise cancelling headphones',
                'long_description' => 'Industry-leading ANC, 30hr battery, touch controls',
                'video_link' => null,
                'sku' => 'SONYWHXM5',
                'price' => 399.99,
                'offer_price' => 349.99,
                'offer_start_date' => '2023-11-01',
                'offer_end_date' => '2023-12-31',
                'product_type' => 'top_product',
                'status' => true,
                'is_approved' => 1,
                'seo_title' => 'Sony WH-1000XM5',
                'seo_description' => 'Premium noise cancelling headphones',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Dell XPS 15',
                'slug' => 'dell-xps-15',
                'thumb_image' => 'uploads/products/dell-xps.jpg',
                'admin_id' => 1,
                'vendor_id' => 0,
                'category_id' => 1,
                'sub_category_id' => 2,
                'child_category_id' => 4,
                'brand_id' => 16,
                'qty' => 40,
                'short_description' => '4K InfinityEdge display',
                'long_description' => '15.6" 4K touchscreen, Intel i9, NVIDIA RTX 4050',
                'video_link' => null,
                'sku' => 'DELLXPS1593',
                'price' => 1799.00,
                'offer_price' => null,
                'offer_start_date' => null,
                'offer_end_date' => null,
                'product_type' => 'best_product',
                'status' => true,
                'is_approved' => 1,
                'seo_title' => 'Dell XPS 15 Laptop',
                'seo_description' => 'Premium Windows laptop',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Canon EOS R5',
                'slug' => 'canon-eos-r5',
                'thumb_image' => 'uploads/products/canon-r5.jpg',
                'admin_id' => 1,
                'vendor_id' => 0,
                'category_id' => 1,
                'sub_category_id' => null,
                'child_category_id' => null,
                'brand_id' => 18,
                'qty' => 30,
                'short_description' => '45MP mirrorless camera',
                'long_description' => '8K video, IBIS, Dual Pixel CMOS AF II',
                'video_link' => null,
                'sku' => 'CANONEOSR5',
                'price' => 3899.00,
                'offer_price' => null,
                'offer_start_date' => null,
                'offer_end_date' => null,
                'product_type' => 'new_arrival',
                'status' => true,
                'is_approved' => 1,
                'seo_title' => 'Canon EOS R5',
                'seo_description' => 'Professional mirrorless camera',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Bose QuietComfort 45',
                'slug' => 'bose-quietcomfort-45',
                'thumb_image' => 'uploads/products/bose-qc45.jpg',
                'admin_id' => 1,
                'vendor_id' => 0,
                'category_id' => 1,
                'sub_category_id' => null,
                'child_category_id' => null,
                'brand_id' => 1,
                'qty' => 60,
                'short_description' => 'Noise cancelling headphones',
                'long_description' => '24hr battery, balanced audio, comfortable fit',
                'video_link' => null,
                'sku' => 'BOSEQC45',
                'price' => 329.00,
                'offer_price' => null,
                'offer_start_date' => null,
                'offer_end_date' => null,
                'product_type' => 'top_product',
                'status' => true,
                'is_approved' => 1,
                'seo_title' => 'Bose QuietComfort 45',
                'seo_description' => 'Premium noise cancelling',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'LG OLED C3',
                'slug' => 'lg-oled-c3',
                'thumb_image' => 'uploads/products/lg-oled.jpg',
                'admin_id' => 1,
                'vendor_id' => 0,
                'category_id' => 1,
                'sub_category_id' => null,
                'child_category_id' => null,
                'brand_id' => 4,
                'qty' => 25,
                'short_description' => '65" 4K OLED TV',
                'long_description' => 'Perfect blacks, α9 Gen6 AI, Dolby Vision IQ',
                'video_link' => null,
                'sku' => 'LGOLED65C3',
                'price' => 2499.00,
                'offer_price' => 2299.00,
                'offer_start_date' => '2023-11-15',
                'offer_end_date' => '2023-12-31',
                'product_type' => 'featured_product',
                'status' => true,
                'is_approved' => 1,
                'seo_title' => 'LG OLED C3 TV',
                'seo_description' => '65" 4K OLED smart TV',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Apple Watch Series 9',
                'slug' => 'apple-watch-series-9',
                'thumb_image' => 'uploads/products/apple-watch.jpg',
                'admin_id' => 1,
                'vendor_id' => 0,
                'category_id' => 1,
                'sub_category_id' => null,
                'child_category_id' => null,
                'brand_id' => 1,
                'qty' => 80,
                'short_description' => 'S9 chip, brighter display',
                'long_description' => 'Advanced health monitoring, crash detection, GPS',
                'video_link' => null,
                'sku' => 'APPAWS941',
                'price' => 429.00,
                'offer_price' => null,
                'offer_start_date' => null,
                'offer_end_date' => null,
                'product_type' => 'new_arrival',
                'status' => true,
                'is_approved' => 1,
                'seo_title' => 'Apple Watch Series 9',
                'seo_description' => 'Latest Apple smartwatch',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Sony PlayStation 5',
                'slug' => 'sony-playstation-5',
                'thumb_image' => 'uploads/products/ps5.jpg',
                'admin_id' => 1,
                'vendor_id' => 0,
                'category_id' => 1,
                'sub_category_id' => null,
                'child_category_id' => null,
                'brand_id' => 3,
                'qty' => 45,
                'short_description' => '4K gaming console',
                'long_description' => 'Ultra-high speed SSD, 3D audio, haptic feedback',
                'video_link' => null,
                'sku' => 'SONYPS5D',
                'price' => 499.99,
                'offer_price' => null,
                'offer_start_date' => null,
                'offer_end_date' => null,
                'product_type' => 'best_product',
                'status' => true,
                'is_approved' => 1,
                'seo_title' => 'PlayStation 5 Console',
                'seo_description' => 'Next-gen gaming console',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Microsoft Surface Pro 9',
                'slug' => 'microsoft-surface-pro-9',
                'thumb_image' => 'uploads/products/surface-pro.jpg',
                'admin_id' => 1,
                'vendor_id' => 0,
                'category_id' => 1,
                'sub_category_id' => 2,
                'child_category_id' => 4,
                'brand_id' => 1,
                'qty' => 35,
                'short_description' => '2-in-1 laptop/tablet',
                'long_description' => '12th Gen Intel Core, Thunderbolt 4, 120Hz display',
                'video_link' => null,
                'sku' => 'MSSP9I5',
                'price' => 1299.00,
                'offer_price' => null,
                'offer_start_date' => null,
                'offer_end_date' => null,
                'product_type' => 'featured_product',
                'status' => true,
                'is_approved' => 1,
                'seo_title' => 'Surface Pro 9',
                'seo_description' => 'Versatile Windows tablet',
                'created_at' => now(),
                'updated_at' => now()
            ],

            // VENDOR PRODUCTS (11-20) - admin_id = 0
            [
                'name' => 'Samsung Galaxy S23 Ultra',
                'slug' => 'samsung-galaxy-s23-ultra',
                'thumb_image' => 'uploads/products/s23ultra.jpg',
                'admin_id' => 0,
                'vendor_id' => 1,
                'category_id' => 1,
                'sub_category_id' => 1,
                'child_category_id' => 1,
                'brand_id' => 2,
                'qty' => 85,
                'short_description' => '200MP camera, S Pen',
                'long_description' => '6.8" AMOLED, Snapdragon 8 Gen 2, 5000mAh',
                'video_link' => 'https://youtu.be/s23ultra',
                'sku' => 'SGS23ULTRA',
                'price' => 1199.99,
                'offer_price' => 1099.99,
                'offer_start_date' => '2023-10-15',
                'offer_end_date' => '2023-11-30',
                'product_type' => 'new_arrival',
                'status' => true,
                'is_approved' => 1,
                'seo_title' => 'Samsung Galaxy S23 Ultra',
                'seo_description' => 'Flagship Android phone',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Nike Air Force 1',
                'slug' => 'nike-air-force-1',
                'thumb_image' => 'uploads/products/airforce1.jpg',
                'admin_id' => 0,
                'vendor_id' => 2,
                'category_id' => 2,
                'sub_category_id' => 3,
                'child_category_id' => null,
                'brand_id' => 5,
                'qty' => 200,
                'short_description' => 'Classic white sneakers',
                'long_description' => 'Leather upper, air cushioning, rubber sole',
                'video_link' => null,
                'sku' => 'NIKEAF101',
                'price' => 110.00,
                'offer_price' => 89.99,
                'offer_start_date' => '2023-11-01',
                'offer_end_date' => '2023-12-31',
                'product_type' => 'best_product',
                'status' => true,
                'is_approved' => 1,
                'seo_title' => 'Nike Air Force 1',
                'seo_description' => 'Iconic basketball shoes',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Levi\'s 501 Jeans',
                'slug' => 'levis-501-jeans',
                'thumb_image' => 'uploads/products/levis501.jpg',
                'admin_id' => 0,
                'vendor_id' => 1,
                'category_id' => 2,
                'sub_category_id' => 3,
                'child_category_id' => 6,
                'brand_id' => 15,
                'qty' => 150,
                'short_description' => 'Original fit jeans',
                'long_description' => 'Straight leg, button fly, 100% cotton',
                'video_link' => null,
                'sku' => 'LEVI501BL',
                'price' => 69.50,
                'offer_price' => null,
                'offer_start_date' => null,
                'offer_end_date' => null,
                'product_type' => 'top_product',
                'status' => true,
                'is_approved' => 1,
                'seo_title' => 'Levi\'s 501 Jeans',
                'seo_description' => 'Classic blue jeans',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Adidas Ultraboost 22',
                'slug' => 'adidas-ultraboost-22',
                'thumb_image' => 'uploads/products/ultraboost.jpg',
                'admin_id' => 0,
                'vendor_id' => 2,
                'category_id' => 2,
                'sub_category_id' => null,
                'child_category_id' => null,
                'brand_id' => 6,
                'qty' => 120,
                'short_description' => 'Responsive running shoes',
                'long_description' => 'Boost cushioning, Primeknit+ upper, Continental rubber',
                'video_link' => null,
                'sku' => 'ADIDUB22',
                'price' => 180.00,
                'offer_price' => 149.99,
                'offer_start_date' => '2023-11-15',
                'offer_end_date' => '2023-12-15',
                'product_type' => 'featured_product',
                'status' => true,
                'is_approved' => 1,
                'seo_title' => 'Adidas Ultraboost 22',
                'seo_description' => 'Premium running shoes',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Zara Oversized Blazer',
                'slug' => 'zara-oversized-blazer',
                'thumb_image' => 'uploads/products/zara-blazer.jpg',
                'admin_id' => 0,
                'vendor_id' => 1,
                'category_id' => 2,
                'sub_category_id' => 4,
                'child_category_id' => 8,
                'brand_id' => 7,
                'qty' => 65,
                'short_description' => 'Trendy oversized fit',
                'long_description' => 'Notched lapels, long sleeves, button cuffs',
                'video_link' => null,
                'sku' => 'ZAROBLAZ',
                'price' => 129.90,
                'offer_price' => null,
                'offer_start_date' => null,
                'offer_end_date' => null,
                'product_type' => 'new_arrival',
                'status' => true,
                'is_approved' => 1,
                'seo_title' => 'Zara Blazer',
                'seo_description' => 'Oversized women\'s blazer',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'KitchenAid Stand Mixer',
                'slug' => 'kitchenaid-stand-mixer',
                'thumb_image' => 'uploads/products/kitchenaid.jpg',
                'admin_id' => 0,
                'vendor_id' => 2,
                'category_id' => 3,
                'sub_category_id' => 6,
                'child_category_id' => null,
                'brand_id' => 10,
                'qty' => 40,
                'short_description' => '5-qt bowl lift mixer',
                'long_description' => '10 speeds, includes 3 attachments, 575W motor',
                'video_link' => null,
                'sku' => 'KITCMIX5',
                'price' => 449.99,
                'offer_price' => null,
                'offer_start_date' => null,
                'offer_end_date' => null,
                'product_type' => 'best_product',
                'status' => true,
                'is_approved' => 1,
                'seo_title' => 'KitchenAid Mixer',
                'seo_description' => 'Professional stand mixer',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'L\'Oréal Skincare Set',
                'slug' => 'loreal-skincare-set',
                'thumb_image' => 'uploads/products/loreal-skincare.jpg',
                'admin_id' => 0,
                'vendor_id' => 1,
                'category_id' => 4,
                'sub_category_id' => 7,
                'child_category_id' => null,
                'brand_id' => 11,
                'qty' => 90,
                'short_description' => 'Complete daily routine',
                'long_description' => 'Cleanser, toner, serum, moisturizer set',
                'video_link' => null,
                'sku' => 'LORESKIN',
                'price' => 59.99,
                'offer_price' => null,
                'offer_start_date' => null,
                'offer_end_date' => null,
                'product_type' => 'top_product',
                'status' => true,
                'is_approved' => 1,
                'seo_title' => 'L\'Oréal Skincare Set',
                'seo_description' => 'Complete skincare routine',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'IKEA KALLAX Shelf',
                'slug' => 'ikea-kallax-shelf',
                'thumb_image' => 'uploads/products/kallax.jpg',
                'admin_id' => 0,
                'vendor_id' => 2,
                'category_id' => 3,
                'sub_category_id' => 5,
                'child_category_id' => null,
                'brand_id' => 9,
                'qty' => 30,
                'short_description' => 'Versatile storage unit',
                'long_description' => '4x4 cube design, can be placed horizontally/vertically',
                'video_link' => null,
                'sku' => 'IKEAKLX4',
                'price' => 69.99,
                'offer_price' => null,
                'offer_start_date' => null,
                'offer_end_date' => null,
                'product_type' => 'featured_product',
                'status' => true,
                'is_approved' => 1,
                'seo_title' => 'IKEA KALLAX Shelf',
                'seo_description' => 'Modular storage solution',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Maybelline Lipstick Set',
                'slug' => 'maybelline-lipstick-set',
                'thumb_image' => 'uploads/products/maybelline-lipstick.jpg',
                'admin_id' => 0,
                'vendor_id' => 1,
                'category_id' => 4,
                'sub_category_id' => 8,
                'child_category_id' => null,
                'brand_id' => 12,
                'qty' => 110,
                'short_description' => '6 vibrant shades',
                'long_description' => 'Creamy matte finish, long-lasting color',
                'video_link' => null,
                'sku' => 'MAYBLIP6',
                'price' => 35.00,
                'offer_price' => null,
                'offer_start_date' => null,
                'offer_end_date' => null,
                'product_type' => 'new_arrival',
                'status' => true,
                'is_approved' => 1,
                'seo_title' => 'Maybelline Lipsticks',
                'seo_description' => 'Set of 6 lipstick shades',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Under Armour Training Shoes',
                'slug' => 'under-armour-training-shoes',
                'thumb_image' => 'uploads/products/ua-shoes.jpg',
                'admin_id' => 0,
                'vendor_id' => 2,
                'category_id' => 5,
                'sub_category_id' => 9,
                'child_category_id' => null,
                'brand_id' => 13,
                'qty' => 75,
                'short_description' => 'Gym workout shoes',
                'long_description' => 'Lightweight cushioning, durable outsole, breathable',
                'video_link' => null,
                'sku' => 'UATRSHOE',
                'price' => 99.99,
                'offer_price' => null,
                'offer_start_date' => null,
                'offer_end_date' => null,
                'product_type' => 'best_product',
                'status' => true,
                'is_approved' => 1,
                'seo_title' => 'Under Armour Training Shoes',
                'seo_description' => 'Performance gym shoes',
                'created_at' => now(),
                'updated_at' => now()
            ]
        ];

         Product::insert($products);
    }
}
